import { writeFileSync } from 'node:fs';
import { calculate } from '../src/engine/calc';
import { ENGINE_VERSION } from '../src/engine/provenance';
import { CASES } from '../tests/fixtures/reference-suite';

let md = `# Validation results\n\nEngine ${ENGINE_VERSION}. Generated by \`npm run validate\`. Reference suite: tests/fixtures/reference-suite.ts\n\n`;
md += `**What this proves:** the engine implements its stated formulas (Q = U·A·ΔT; 1.08·CFM·ΔT; latent via 4842·CFM·ΔW/7000; CFM = ACH·V/60) on hand-derived cases. It does **not** show agreement with ACCA Manual J (see "ACCA / Long House references" below).\n\n`;
md += `| Case | What it checks | Quantity | Expected | Actual | Diff | Tolerance | Result |\n|---|---|---|---|---|---|---|---|\n`;
let fail = false;
for (const c of CASES) {
  const res = calculate(c.build());
  const r = res.rooms; const sum = (k: 'heating' | 'coolingSensible' | 'coolingLatent') => (r.every(x => x[k]) ? r.reduce((s, x) => s + x[k]!.btuh, 0) : NaN);
  for (const [name, key] of [['heating', 'heating'], ['cooling sensible', 'coolingSensible'], ['cooling latent', 'coolingLatent']] as const) {
    const exp = c.expected[key], act = sum(key), d = act - exp, ok = Math.abs(d) <= c.tol; fail ||= !ok;
    md += `| ${c.id} | ${c.what} | ${name} | ${exp.toFixed(3)} | ${Number.isNaN(act) ? 'not calculated' : act.toFixed(3)} | ${d.toExponential(2)} | ±${c.tol} | ${ok ? 'PASS' : 'FAIL'} |\n`;
  }
}
md += `\nSource of expected values for every case: hand-derived first-principles arithmetic in this repository.\n\n## ACCA / Long House references\nSTATUS: NOT RUN. www.acca.org was unreachable from the build environment (network policy) and downloads sit behind ACCA terms. See docs/VALIDATION_PLAN.md and docs/ENGINEERING_REVIEW.md.\n`;
writeFileSync('docs/VALIDATION_RESULTS.md', md); console.log(md); process.exit(fail ? 1 : 0);
