import { writeFileSync } from 'node:fs';
import { calculate } from '../src/engine/calc';
import { ENGINE_VERSION } from '../src/engine/provenance';
import { buildProject, EXPECTED, FIXTURE_ID, FIXTURE_SOURCE, TOLERANCE_BTUH } from '../tests/fixtures/analytic-box-room';

const r = calculate(buildProject()).rooms[0];
const rows = [['heating', EXPECTED.heating, r.heating!.btuh], ['cooling sensible', EXPECTED.coolingSensible, r.coolingSensible!.btuh], ['cooling latent', EXPECTED.coolingLatent, r.coolingLatent!.btuh]] as const;
let md = `# Validation results\n\nEngine ${ENGINE_VERSION}. Generated by \`npm run validate\`.\n\n## ${FIXTURE_ID} — analytic box room\nSource: ${FIXTURE_SOURCE}\nInputs: tests/fixtures/analytic-box-room.ts\nTolerance: ±${TOLERANCE_BTUH} Btu/h\n\n| Quantity | Expected | Actual | Diff | Result |\n|---|---|---|---|---|\n`;
let fail = false;
for (const [n, e, a] of rows) { const d = a - e; const ok = Math.abs(d) < TOLERANCE_BTUH; fail ||= !ok; md += `| ${n} | ${e.toFixed(3)} | ${a.toFixed(3)} | ${d.toExponential(2)} | ${ok ? 'PASS' : 'FAIL'} |\n`; }
md += `\n## ACCA / Long House references\nSTATUS: NOT RUN. www.acca.org was unreachable from the build environment (network policy), and downloads sit behind ACCA terms. See docs/VALIDATION_PLAN.md.\n`;
writeFileSync('docs/VALIDATION_RESULTS.md', md); console.log(md); process.exit(fail ? 1 : 0);
